### ISSUE TITLE
Unable to report a new issue as a student

### ISSUE THREAD

**Issue by mudrd8mz** [KQMATH/moodle-block_quizqtracker#6]
When I attempt a quiz as the admin, I can see the side block "Quiz Question Tracker" with the form "If you have feedback for a question, please fill in the form below." etc.

But when I attempt the same quiz as the regular student, I cannot see that block.

Where and how can the teacher make it so that students can report new issues? I was expecting to see a capability or so to control this ...

**Comment by andstor** [comment]
This is probably related to a setting that needs to be made in the actual quiz activity, in order for students to be able to see blocks.

Go to the "Edit settings" for the quiz activity.  Then, under "Appearance", the "Show blocks during quiz attempts" needs to be set to `Yes`.

**Comment by mudrd8mz** [comment]
Oh yes indeed! Sorry I'd missed this important detail.
